-- Portfolio database schema.
-- Derived from the API models (api/src/models) and queries (api/src/db) — those are
-- the contract; if a column changes here, the API and the regenerated web client
-- must change with it.

CREATE TYPE proficiency AS ENUM ('Beginner', 'Intermediate', 'Advanced', 'Expert');

CREATE TABLE jobs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date date NOT NULL,
    end_date date,
    is_current_job boolean NOT NULL DEFAULT false,
    company_name text NOT NULL,
    company_website text NOT NULL,
    description text NOT NULL,
    roles text NOT NULL,
    responsibilities text NOT NULL
);

CREATE TABLE skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text NOT NULL,
    official_site_url text NOT NULL,
    proficiency proficiency NOT NULL,
    parent_id integer REFERENCES skills (id)
);

CREATE TABLE projects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL,
    github_url text,
    job_id integer REFERENCES jobs (id)
);

CREATE TABLE projects_skills (
    project_id integer NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    skill_id integer NOT NULL REFERENCES skills (id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, skill_id)
);
